(function(g){var window=this;'use strict';var pmb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");c===-1&&(c=a.length);var d=a[0]==="-"?"-":"";d&&(a=a.substring(1));return d+(0,g.Rbb)("0",Math.max(0,b-c))+a},qmb=function(){return{J:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},X:[{J:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},rmb=function(){return{J:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},X:[{J:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},tmb=function(a){typeof a==="number"?(this.date=smb(a,0,1),Q5(this,1)):g.Ta(a)?(this.date=smb(a.getFullYear(),a.getMonth(),a.getDate()),Q5(this,a.getDate())):(this.date=new Date(g.Za()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),Q5(this,a))},smb=function(a,b,c){b=new Date(a,b,c);
a>=0&&a<100&&b.setFullYear(b.getFullYear()-1900);return b},Q5=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},R5=function(a,b){g.tS.call(this,a,{J:"div",
S:"ytp-reminder-menu",Y:{role:"menu",tabindex:"-1"},X:[{J:"div",S:"ytp-reminder-menu-contents",X:[{J:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.j=b;this.C=[];this.menuPopupRenderer=void 0;this.items=this.Da("ytp-reminder-menu-items");this.hide()},umb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},S5=function(a){g.S.call(this,{J:"div",
X:[{J:"button",Ka:["ytp-offline-slate-button","ytp-button"],X:[{J:"div",S:"ytp-offline-slate-button-icon",ya:"{{icon}}"},{J:"div",S:"ytp-offline-slate-button-text",ya:"{{text}}"}]}]});this.K=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.G=this.Da("ytp-offline-slate-button"))&&this.T(this.G,"click",this.L);this.hide()},wmb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.Q(c,vmb)?a.upcomingEventReminderButtonRenderer=g.Q(c,vmb):c&&g.Q(c,vmb)||(a.upcomingEventReminderButtonRenderer=null);T5(a)},T5=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.Px(b.toggledText):"";a.update({text:c,icon:xmb(b.toggledIcon)})}else c=b.defaultText?g.Px(b.defaultText):"",a.update({text:c,icon:xmb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=ymb(a))?(c=b.text?g.Px(b.text):"",a.update({text:c,icon:xmb(b.icon)}),a.show()):a.hide():a.hide()},Amb=function(a,b,c){a.D||(a.D=new g.yv(a.K.V().Dl));
var d={context:g.Fu(a.D.config_||g.Eu())};g.Ww()&&(d.context.clientScreenNonce=g.Ww());d.params=c;g.zv(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){zmb(a)},
onTimeout:function(){zmb(a)}})},zmb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,T5(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,T5(a))},xmb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return qmb();case "NOTIFICATIONS_NONE":return rmb();case "NOTIFICATIONS_ACTIVE":return g.Xx();default:return null}},ymb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.x(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.Q(c.value,Bmb))&&c.state===b&&c.button&&g.Q(c.button,g.XJ))return g.Q(c.button,g.XJ);return null},Cmb=function(a){g.S.call(this,{J:"div",
S:"ytp-offline-slate",X:[{J:"div",S:"ytp-offline-slate-background"},{J:"div",S:"ytp-offline-slate-bar",X:[{J:"span",S:"ytp-offline-slate-icon",X:[{J:"svg",Y:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},X:[{J:"path",Y:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{J:"circle",Y:{cx:"12",cy:"12",r:"3"}}]}]},{J:"span",S:"ytp-offline-slate-messages",X:[{J:"div",S:"ytp-offline-slate-main-text",Y:{"aria-label":"{{label}}"},ya:"{{mainText}}"},{J:"div",S:"ytp-offline-slate-subtitle-text",ya:"{{subtitleText}}"}]},{J:"span",S:"ytp-offline-slate-buttons"}]},{J:"button",Ka:["ytp-offline-slate-close-button","ytp-button"],X:[g.Tx()]},{J:"button",Ka:["ytp-offline-slate-open-button","ytp-button"],X:[g.Sx()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Da("ytp-offline-slate-background");
this.C=this.Da("ytp-offline-slate-bar");this.G=new g.pp(function(){g.xp(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.L=!1;this.D=new g.pp(function(){g.xp(b.element,"ytp-offline-slate-collapsed")},15E3);
g.P(this,this.D);g.P(this,this.G);this.countdownTimer=new g.pp(this.T3,1E3,this);this.T(a,"presentingplayerstatechange",this.W3);this.T(a,"livestatedata",this.Ta);this.T(this.Da("ytp-offline-slate-close-button"),"click",function(){g.xp(b.element,"ytp-offline-slate-collapsed")});
this.T(this.Da("ytp-offline-slate-open-button"),"click",function(){g.zp(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Ta(a);a=this.api.getPresentingPlayerType()===8&&!this.getVideoData().Jm;var c=this.api.getPresentingPlayerType()===8;g.Bp(this.element,"ytp-offline-slate-premiere-trailer",a);g.Bp(this.element,"ytp-offline-slate-hide-background",c)},Dmb=function(a,b,c){if(b){var d=b.subtitleText!=null?g.Px(b.subtitleText):"";
c=c?c:b.mainText!=null?g.Px(b.mainText):"";var e,f,h,l;b=(l=(e=b.mainText)==null?void 0:(f=e.accessibility)==null?void 0:(h=f.accessibilityData)==null?void 0:h.label)!=null?l:c;a.update({mainText:c,subtitleText:d,label:b});g.Bp(a.element,"ytp-offline-slate-single-text-line",!d);g.Bp(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},U5=function(a,b){var c=(0,g.Ut)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},Jmb=function(a){g.fY.call(this,a);
var b=this;this.U=!1;this.W=0;this.G=!1;this.B=new g.pp(function(){Emb(b)},0);
this.j=this.heartbeatParams=null;this.D=!1;this.L=new g.vh(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.qa=new g.yv(void 0);this.attestationResponse=Promise.resolve(void 0);this.Z=Promise.resolve(void 0);this.utcOffsetMinutes=-(new tmb).getTimezoneOffset();this.C=new g.cG(this);g.P(this,this.B);g.P(this,this.C);Fmb(this);Gmb(this);this.C.T(a,"heartbeatparams",this.YG);this.C.T(a,"presentingplayerstatechange",this.w5);this.C.T(a,"videoplayerreset",this.x5);this.C.T(a,g.CE("heartbeat"),
this.onCueRangeEnter);this.D&&this.j&&Hmb(this,void 0,this.j);var c=new g.AE(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.AE(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.gf([c,d]);Imb(this)},Imb=function(a){var b=a.getVideoData();
!b.N("use_rta_only_for_player")&&b.xk&&(b=b.botguardData)&&g.VL(b,a.player.V())},Kmb=function(a){var b,c;
return g.I(function(d){if(d.j==1)return g.G(d,g.Yua(),2);if(!d.B)return a.sequenceNumber>=3?d.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):d.return(void 0);b=a.getVideoData();c={};return d.return(g.Xua((c.cpn=b.clientPlaybackNonce,c.encryptedVideoId=b.videoId||"",c),1500))})},Fmb=function(a){var b=a.getVideoData();
if(b.xk)if(b.N("use_rta_for_player_hb"))a.attestationResponse=Kmb(a);else if(b=new g.SCa(b),g.RL.isInitialized()||a.sequenceNumber>=3){var c=Promise,d=c.resolve,e=null;if(b.videoData.Kr){var f=g.TCa(b);if(f){e={};var h={};f=f.split("&");f=g.x(f);for(var l=f.next();!l.done;l=f.next())l=l.value.split("="),l.length===2&&(h[l[0]]=l[1]);h.r1a&&(e.webResponse=h.r1a);h.r1c&&(e.error=Lmb[Number(h.r1c)]);e.challenge=b.videoData.Kr}}a.attestationResponse=d.call(c,e||void 0)}},Mmb=function(a){var b=a.getVideoData();
if(!g.uR(a.getVideoData())||b.BV)return!1;if(b.useInnertubeDrmService()&&b.G){a=b.G.flavor==="playready"&&b.N("html5_innertube_heartbeats_for_playready");var c=b.G.flavor==="widevine"&&b.N("html5_innertube_heartbeats_for_widevine");b=g.TO(b.G)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},Nmb=function(a){if(Mmb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.uR(a.getVideoData())&&b.useInnertubeDrmService()&&!b.El&&!b.zF?!1:!!b.heartbeatToken},V5=function(a,b){if(!a.B.isActive()&&a.U){var c=a.getVideoData();
if(Nmb(a)||c.isLivePlayback){if(b===void 0)if(a.G)if(a.D)b=7500;else{var d;b=((d=a.heartbeatParams)==null?0:d.interval)?a.heartbeatParams.interval*1E3:a.getVideoData().tV||6E4}else b=1E3;a.B.start(b)}}},Rmb=function(a,b,c){b.Zn&&(c=g.bj(c,{internalipoverride:b.Zn}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.tb&&(d.kpt=b.tb);c=g.bj(c,d);g.Qr(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&W5(a)){a.L.reset();a.sequenceNumber++;e=e.responseText;var f=Omb(e);if(f){a.player.gb("onHeartbeat",f);var h=f.status==="ok"?f.stop_heartbeat?2:0:f.status==="stop"?1:f.status==="live_stream_offline"?0:-1}else h=(h=e.match(Pmb))?h[1]==="0"?0:1:-1;Qmb(a,void 0,f,e,h)}},
onError:function(e){W5(a)&&X5(a,!0,"net-"+e.status)},
onTimeout:function(){W5(a)&&X5(a,!0,"timeout")},
withCredentials:!0})},Emb=function(a){var b,c;
g.I(function(d){b=a.player.V();c=a.getVideoData();if(!W5(a))return d.return();if(Mmb(a))return Smb(a,b,c),d.Ga(0);Fmb(a);return g.G(d,Tmb(a,b,c),0)})},Smb=function(a,b,c){var d;
if((d=a.heartbeatParams)!=null&&d.url){var e=g.bj(a.heartbeatParams.url,{request_id:g.cra()});c.ra&&(e=g.bj(e,{vvt:c.ra}),c.mdxEnvironment&&(e=g.bj(e,{mdx_environment:c.mdxEnvironment})));g.jQ(b,c.oauthToken).then(function(f){f&&(e=g.bj(e,{access_token:f}));Rmb(a,c,e)})}},W5=function(a){var b=a.getVideoData();
return a.player.getPresentingPlayerType()===3||g.T(a.player.getPlayerStateObject(a.getPlayerType()),4)?!1:Nmb(a)||b.isLivePlayback?!0:(Y5(a),!1)},Tmb=function(a,b,c){var d,e,f,h,l,m,n,p,q,r,t,u,y,A,C,F,H,K,N,W;
return g.I(function(V){if(V.j==1)return d="player/heartbeat",f={videoId:c.videoId,sequenceNumber:a.sequenceNumber,heartbeatServerData:(e=a.ra)!=null?e:c.heartbeatServerData},a.Z=a.attestationResponse,c.xk?g.G(V,a.Z,3):V.Ga(2);V.j!=2&&(f.attestationResponse=V.B);h=g.RR(c);m=(l=h.client)!=null?l:{};m.utcOffsetMinutes=a.utcOffsetMinutes;f.context=h;f.cpn=c.clientPlaybackNonce;if(n=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)m.timeZone=n;p={heartbeatChecks:[]};
if(q=c.getPlayerResponse())c.heartbeatToken&&(f.heartbeatToken=c.heartbeatToken),(r=q.playabilityStatus)&&(t=r.liveStreamability)&&t.liveStreamabilityRenderer&&p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.VD(b)&&(p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),u=Umb(a),y={},u!==null&&(y.clientPlayerPositionUtcMillis=u),C=(A=a.player.Bb())==null?void 0:g.qY(A),H=((F=C)==null?void 0:F.freePreviewWatchedDuration)||
0,H>0&&(y.freePreviewWatchedDuration={seconds:""+H}),p.unpluggedParams=y);f.heartbeatRequestParams=p;c.isLivePlayback?(K=Umb(a),K!==null&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition={utcTimeMillis:K})):b.N("enable_heartbeat_vod_playback_position")&&(N=Vmb(a),N!==null&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition={streamTimeMillis:N}));a.player.publish("heartbeatRequest",f);W={timeout:3E4,onSuccess:function(da){if(!a.B.isActive()&&W5(a)){var na=
a.getVideoData(),X=na.xk&&a.Z==null,R;na.xk=!((R=da.heartbeatAttestationConfig)==null||!R.requiresAttestation)||X;X=da.playabilityStatus;R=JSON.stringify(X)||"{}";da.authenticationMismatch&&a.player.oa("authshear",{});var Y=-1;var v=da.playabilityStatus;v&&(a.player.gb("onHeartbeat",v),v.status==="OK"?Y=da.stopHeartbeat?2:0:v.status==="UNPLAYABLE"?Y=1:v.status==="LIVE_STREAM_OFFLINE"&&(Y=0));a.sequenceNumber&&Y===-1||a.L.reset();a.sequenceNumber++;da.heartbeatServerData&&(a.ra=da.heartbeatServerData);
na.sG=da;(v=da.playerCueRangeSet)&&g.aR(na,v);da.playerCueRanges&&da.playerCueRanges.length>0&&(na.cueRanges=da.playerCueRanges);var U,$a;((U=da.progressBarConfig)==null?0:U.progressBarStartPosition)&&(($a=da.progressBarConfig)==null?0:$a.progressBarEndPosition)&&(na.progressBarStartPosition=da.progressBarConfig.progressBarStartPosition,na.progressBarEndPosition=da.progressBarConfig.progressBarEndPosition);na.compositeLiveIngestionOffsetToken=da.compositeLiveIngestionOffsetToken;da.compositeLiveStatusToken!==
na.compositeLiveStatusToken&&(na.compositeLiveStatusToken=da.compositeLiveStatusToken);na.publish("dataupdated");Qmb(a,da,X,R,Y)}},
onError:function(da){W5(a)&&X5(a,!0,"net-"+da.status)},
onTimeout:function(){W5(a)&&X5(a,!0,"timeout")}};
g.jQ(b,g.LR(c)).then(function(da){da&&(W.JX="Bearer "+da);g.zv(a.qa,d,f,W)});
g.va(V)})},Qmb=function(a,b,c,d,e){e===-1?(c="decode "+g.vc(d,3),X5(a,!1,c)):e===2?(Y5(a),a.G=!0):(a.W=0,a.B.stop(),e===1?(a.G=!1,c&&c.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&a.player.qp(!0),e="pe."+(c==null?void 0:c.errorCode)+";ps."+(c==null?void 0:c.status),a.player.vg("heartbeat.stop",2,a.eg(d),e),g.Ct("heartbeatActionPlayerHalted",Wmb(c)),(b==null?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.Q(b,g.jR))&&Xmb(a,d,c,{itct:b==null?void 0:b.clickTrackingParams}))):(a.G=
!0,d=0,a.D&&c&&(d=Hmb(a,b,c),a.player.publish("livestatedata",c)),d?V5(a,d):V5(a)))},Hmb=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&d.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
b=Ymb(a,b,d);var f=a.getVideoData(),h=a.player.getPlayerStateObject(a.getPlayerType()),l=h.isPlaying()&&!g.AR(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.V().Xb()){var m,n=((m=a.player.Le())==null?void 0:m.wc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.oa("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.Q(d.streamTransitionEndpoint,g.jR);if((d&&d.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&Xmb(a,e,c))return b;if(c.status.toUpperCase()==="OK"){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&e!=null;if(!g.xR(f)||l){var p={video_id:f.videoId};f.RI&&(p.is_live_destination="1");a.player.N("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.getWatchNextResponse());p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;
p.force_gvi=f.Yn;p.An=f.An;f.L&&(p.vss_credentials_token=f.L,p.vss_credentials_token_type=f.Sn);f.ra&&(p.vvt=f.ra);d=void 0;g.xR(f)?l&&(d=new U5("broadcastIdChanged",m+","+e),a.xL("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new U5("formatsReceived",""+e)),a.xL("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Ng("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.L=!0,a.Eb&&a.api.JC()):h.isBuffering()&&(f=((p=a.player.Le())==null?void 0:p.wc())||{},a.player.oa("hbse",f,!0),a.player.JC(),a.player.gb("onLiveMediaEnded",c)));return b},Ymb=function(a,b,c){return a.player.N("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(b==null?void 0:b.pollDelayMs))?a:(c=Number(c==null?void 0:c.pollDelayMs))?c:0},X5=function(a,b,c){var d=a.player.V();
if(!a.B.isActive()){a.B.stop();a.W++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.zV||b&&!g.uR(a.getVideoData())&&!Nmb(a)&&f.isLivePlayback)f=!1;else{var h,l;((l=a.heartbeatParams)==null?0:l.retries)?h=a.heartbeatParams.retries:h=f.yV||5;f=a.W>=h}f?(g.Ct("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:Wmb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.vg(e,1,"Reprodu\u00e7\u00e3o de v\u00eddeo interrompida. Tente novamente.",c):a.player.vg(e,
1,"Ocorreu um erro ao licenciar este v\u00eddeo.",c)):(d.N("html5_report_non_fatal_heartbeat_error")&&a.player.gt(e,{msg:c}),V5(a,a.L.getValue()),g.wh(a.L))}},Wmb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},Y5=function(a){a.W=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},Gmb=function(a){var b=a.getVideoData(),c=a.player.V();
if(b.isLivePlayback)if(g.jP(c.G)){a.D=!0;a.U=!0;if(!g.XD(c)||g.VD(c))a.offlineSlate=new Cmb(a.player),g.P(a,a.offlineSlate),g.pS(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;((d=a.j)==null?void 0:d.status)!=="UNPLAYABLE"&&(a.j?(d=Ymb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?V5(a,d):V5(a,7500):V5(a,1E3))}else a.player.vg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Zb(b.Ea,"heartbeat")&&a.player.Ng("heartbeat",a.getPlayerType())},Xmb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.Hp(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.LR(a.getVideoData())),a.xL("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},Umb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(a*1E3):null},Vmb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(a*1E3):null},Omb=function(a){try{var b=JSON.parse(a);
return b!=null?b:void 0}catch(c){}},Zmb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
Zmb={ERAS:["a.C.","d.C."],ERANAMES:["antes de Cristo","depois de Cristo"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),STANDALONEMONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),SHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),STANDALONESHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),
WEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),STANDALONEWEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),SHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),STANDALONESHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),NARROWWEEKDAYS:"DSTQQSS".split(""),STANDALONENARROWWEEKDAYS:"DSTQQSS".split(""),SHORTQUARTERS:["T1","T2","T3","T4"],QUARTERS:["1\u00ba trimestre",
"2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, d 'de' MMMM 'de' y","d 'de' MMMM 'de' y","d 'de' MMM 'de' y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} '\u00e0s' {0}","{1} '\u00e0s' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
var Lmb=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=tmb.prototype;g.k.MY=Zmb.FIRSTDAYOFWEEK;g.k.OY=Zmb.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new tmb(this.date);a.MY=this.MY;a.OY=this.OY;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+a.years*12,c=this.getYear()+Math.floor(b/12);b%=12;b<0&&(b+=12);a:{switch(b){case 1:var d=c%4!=0||c%100==0&&c%400!=0?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=c>=0&&c<=99?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+a.days*864E5),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),Q5(this,a.getDate()))};
g.k.toString=function(){var a=this.getFullYear(),b=a<0?"-":a>=1E4?"+":"";return[b+pmb(Math.abs(a),b?6:4),pmb(this.getMonth()+1,2),pmb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var $mb=new g.Rq("addUpcomingEventReminderEndpoint");var anb=new g.Rq("removeUpcomingEventReminderEndpoint");var bnb=new g.Rq("updateUpcomingEventReminderButtonStateCommand");var vmb=new g.Rq("upcomingEventReminderButtonRenderer"),Bmb=new g.Rq("upcomingEventReminderButtonStateRenderer");g.w(R5,g.tS);
R5.prototype.updateMenuItems=function(){var a=this,b=umb(this),c=0;c=0;for(var d={};c<b.length;d={b_:void 0},c++){var e=this.C[c];e||(e=new g.S({J:"div",S:"ytp-reminder-menu-item",Y:{role:"menuitem",tabindex:"0"},X:[{J:"div",S:"ytp-reminder-menu-item-icon",ya:"{{icon}}"},{J:"div",S:"ytp-reminder-menu-item-label",ya:"{{text}}"}]}),d.b_=c,e.listen("click",function(h){return function(){var l=h.b_;a.Pb();l=umb(a)[l];a.publish("reminderMenuItemClicked",l.serviceEndpoint||l.command)}}(d)),e.Ha(this.items),
this.C[c]=e);
var f=b[c];d=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":d=qmb();break;case "NOTIFICATIONS_NONE":d=rmb();break;case "NOTIFICATIONS_ACTIVE":d=g.Xx()}f=f.text?g.Px(f.text):"";e.update({icon:d,text:f})}for(;c<this.C.length;)this.C.pop().dispose();c===0?this.Pb():this.kd(this.j)};
R5.prototype.hide=function(){this.j&&this.j.removeAttribute("aria-haspopup");g.tS.prototype.hide.call(this)};
R5.prototype.show=function(){this.j&&this.j.setAttribute("aria-haspopup","true");g.tS.prototype.show.call(this)};
R5.prototype.xa=function(){g.lb(this.C);g.tS.prototype.xa.call(this)};g.w(S5,g.S);
S5.prototype.L=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;T5(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Eb)this.j.Pb();else{var b=ymb(this);b&&this.C(b.serviceEndpoint||b.command);b=((a=g.Q(b==null?void 0:b.command,g.Qy))==null?void 0:a.commands)||[];a:{a=g.x(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=(b=g.Q(c.value,g.gdb))==
null?void 0:(d=b.popup)==null?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new R5(this.K,this.G),this.j.Ha(this.element),g.P(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;b.updateMenuItems()}};
S5.prototype.C=function(a){var b=g.Q(a,$mb),c=g.Q(a,anb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(Amb(this,e,d.params),a=g.x(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.Q(b,bnb)){this.B=g.Q(b,bnb).state;T5(this);break}}};g.w(Cmb,g.S);g.k=Cmb.prototype;g.k.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Ta=function(a){var b,c,d=a==null?void 0:(b=a.liveStreamability)==null?void 0:(c=b.liveStreamabilityRenderer)==null?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.T3():Dmb(this,b);var e,f,h,l;if(c=a==null?void 0:(e=a.liveStreamability)==null?void 0:(f=e.liveStreamabilityRenderer)==null?void 0:(h=f.offlineSlate)==null?void 0:(l=h.liveStreamOfflineSlateRenderer)==null?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new S5(this.api),this.j.Ha(this.Da("ytp-offline-slate-buttons")),g.P(this,this.j)),wmb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&wmb(this.j,null,null);this.B=a}else this.B=null;this.W3()};
g.k.W3=function(a){if(this.api.getPresentingPlayerType()===8)var b=!0;else{var c=this.api.getPlayerStateObject(),d=this.getVideoData();b=d.isLivePlayback&&(c.isBuffering()||g.T(c,2)||g.T(c,64));var e=d.autonavState===2&&g.T(c,2);c=c.isPlaying()&&!g.AR(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Eb?(a==null?0:g.Oy(a,2))&&!this.getVideoData().Jm&&(g.zp(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.zp(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),
this.D.start(),this.api.publish("offlineslatestatechange"),this.L&&this.api.JC()):this.Eb&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.k.T3=function(){var a,b,c,d,e=(a=this.B)==null?void 0:(b=a.liveStreamability)==null?void 0:(c=b.liveStreamabilityRenderer)==null?void 0:(d=c.offlineSlate)==null?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Za()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(Dmb(this,e),this.countdownTimer.stop()):(Dmb(this,e,g.Xy(b-a)),g.qp(this.countdownTimer)))};
g.k.xa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.S.prototype.xa.call(this)};U5.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
U5.prototype.isExpired=function(){return(0,g.Ut)()-this.C>6E4};
U5.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.w(Jmb,g.fY);g.k=Jmb.prototype;g.k.xa=function(){Y5(this);this.player.bf("heartbeat");g.fY.prototype.xa.call(this)};
g.k.onCueRangeEnter=function(){this.U=!0;V5(this,2E3)};
g.k.YG=function(a){this.heartbeatParams=a;V5(this,2E3)};
g.k.w5=function(a){var b;this.player.getPresentingPlayerType()!==8&&((b=this.j)==null?void 0:b.status)!=="UNPLAYABLE"&&(g.T(a.state,2)||g.T(a.state,64)?(Y5(this),this.D&&(this.U=!0,V5(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&V5(this,2E3))};
g.k.x5=function(){this.player.getPresentingPlayerType()!==3&&V5(this,2E3)};
g.k.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Nn=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.xL=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.Ct("heartbeatActionPlayerTransitioned",a)};
g.k.eg=function(a){var b="LICENSE",c=Omb(a);if(c)return c.reason||g.zY[b]||"";(a=a.match(Pmb))&&(a=Number(a[1]))&&(b=g.Kxa(a));return g.zY[b]||""};
g.k.mG=function(){return!!this.offlineSlate&&this.offlineSlate.Eb};
var Pmb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.eY("heartbeat",Jmb);})(_yt_player);
